version: '3.3'

services:
  # app:
  #   build: .
  #   container_name: app
  #   restart: unless-stopped
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - ./core/.env
  #   networks:
  #     - car-accident-net
    # depends_on:
    #   - db

  db:
    image: mariadb
    container_name: app-db
    restart: unless-stopped
    env_file:
      - ./core/.env
    ports:
      - "3306:3306"
    networks:
      - car-accident-net
    volumes:
      - ../資料庫管理:/home/資料庫管理/

networks:
  car-accident-net:
