# Generated by Django 5.0.6 on 2024-06-09 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "錯誤型態",
                    models.CharField(
                        choices=[
                            ("資料不正確", "資料不正確"),
                            ("資料遺漏", "資料遺漏"),
                            ("系統錯誤", "系統錯誤"),
                            ("圖表錯誤", "圖表錯誤"),
                            ("其他", "其他"),
                        ],
                        default="資料不正確",
                        max_length=5,
                        verbose_name="錯誤類型",
                    ),
                ),
                ("錯誤描述", models.TextField(verbose_name="錯誤描述")),
                (
                    "查詢內容",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="查詢內容"
                    ),
                ),
                (
                    "錯誤頁面",
                    models.CharField(
                        max_length=200, verbose_name="錯誤發現於哪個頁面或功能"
                    ),
                ),
                (
                    "具體位置描述",
                    models.TextField(
                        blank=True, null=True, verbose_name="具體位置描述"
                    ),
                ),
                (
                    "錯誤截圖",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="error_screenshots/",
                        verbose_name="錯誤截圖",
                    ),
                ),
                (
                    "其他說明",
                    models.TextField(blank=True, null=True, verbose_name="其他說明"),
                ),
                (
                    "回報日期",
                    models.DateTimeField(auto_now_add=True, verbose_name="回報日期"),
                ),
                (
                    "處理狀態",
                    models.CharField(
                        choices=[
                            ("未處理", "未處理"),
                            ("已處理", "已處理"),
                            ("駁回", "駁回"),
                        ],
                        default="未處理",
                        max_length=5,
                        verbose_name="處理狀態",
                    ),
                ),
                (
                    "用戶",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "錯誤回報",
                "verbose_name_plural": "錯誤回報",
            },
        ),
    ]
