# Generated by Django 5.0.6 on 2024-06-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="errorreport",
            options={
                "permissions": [
                    ("check_repair", "Can selected repair the status of report"),
                    ("check_overrule", "Can selected overrule the status of report"),
                ],
                "verbose_name": "錯誤回報",
                "verbose_name_plural": "錯誤回報",
            },
        ),
    ]
