# Generated by Django 5.0.6 on 2024-06-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UnitName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("處理單位名稱警局層", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "處理單位名稱警局層",
                "verbose_name_plural": "處理單位名稱警局層",
                "db_table_comment": "處理單位名稱警局層表",
            },
        ),
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("當事者區分_類別_大類別名稱_車種", models.CharField(max_length=15)),
            ],
            options={
                "verbose_name": "當事者區分_類別_大類別名稱_車種",
                "verbose_name_plural": "當事者區分_類別_大類別名稱_車種",
                "db_table_comment": "當事者區分_類別_大類別名稱_車種表",
            },
        ),
    ]
