# Generated by Django 5.0.6 on 2024-06-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UnitName",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "處理單位名稱警局層",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "unit_name",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "當事者區分_類別_大類別名稱_車種",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
            ],
            options={
                "db_table": "vehicle_type",
                "managed": False,
            },
        ),
    ]
