# Generated by Django 5.0.6 on 2024-06-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transport_subsidiary", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unitname",
            options={
                "managed": True,
                "verbose_name": "處理單位名稱警局層",
                "verbose_name_plural": "處理單位名稱警局層",
            },
        ),
        migrations.AlterModelOptions(
            name="vehicletype",
            options={
                "managed": True,
                "verbose_name": "當事者區分_類別_大類別名稱_車種",
                "verbose_name_plural": "當事者區分_類別_大類別名稱_車種",
            },
        ),
    ]
