# Generated by Django 5.0.6 on 2024-06-15 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_subsidiary', '0002_alter_unitname_options_alter_vehicletype_options'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='unitname',
            table_comment='處理單位名稱警局層表',
        ),
        migrations.AlterModelTableComment(
            name='vehicletype',
            table_comment='當事者區分_類別_大類別名稱_車種表',
        ),
    ]
