# Generated by Django 5.0.6 on 2024-06-03 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transport_subsidiary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccidentRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("發生年度", models.CharField(max_length=4)),
                ("發生月份", models.CharField(max_length=2)),
                ("發生日期", models.CharField(max_length=8)),
                ("發生時間", models.CharField(max_length=6)),
                ("事故類別名稱", models.CharField(max_length=2)),
                ("發生地點", models.CharField(max_length=80)),
                (
                    "天候名稱",
                    models.CharField(
                        choices=[
                            ("晴", "晴"),
                            ("雪", "雪"),
                            ("風沙", "風沙"),
                            ("暴雨", "暴雨"),
                            ("強風", "強風"),
                            ("雨", "雨"),
                            ("陰", "陰"),
                            ("霧或煙", "霧或煙"),
                        ],
                        default="晴",
                        max_length=3,
                    ),
                ),
                (
                    "光線名稱",
                    models.CharField(
                        choices=[
                            (
                                "夜間(或隧道、地下道、涵洞)有照明",
                                "夜間(或隧道、地下道、涵洞)有照明",
                            ),
                            (
                                "夜間(或隧道、地下道、涵洞)無照明",
                                "夜間(或隧道、地下道、涵洞)無照明",
                            ),
                            ("有照明未開啟或故障", "有照明未開啟或故障"),
                            ("晨或暮光", "晨或暮光"),
                            ("日間自然光線", "日間自然光線"),
                        ],
                        default="夜間(或隧道、地下道、涵洞)有照明",
                        max_length=20,
                    ),
                ),
                ("經度", models.DecimalField(decimal_places=6, max_digits=9)),
                ("緯度", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "處理單位名稱警局層",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport_subsidiary.unitname",
                    ),
                ),
            ],
            options={
                "verbose_name": "事故紀錄",
                "verbose_name_plural": "事故紀錄",
                "db_table_comment": "事故紀錄表",
            },
        ),
        migrations.CreateModel(
            name="CauseAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("肇因研判大類別名稱_主要", models.CharField(max_length=15)),
                ("肇因研判子類別名稱_主要", models.CharField(max_length=25)),
                ("肇因研判子類別名稱_個別", models.CharField(max_length=25)),
                ("肇事逃逸類別名稱_是否肇逃", models.CharField(max_length=2)),
                (
                    "accident_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.accidentrecords",
                    ),
                ),
            ],
            options={
                "verbose_name": "原因分析",
                "verbose_name_plural": "原因分析",
                "db_table_comment": "原因分析表",
            },
        ),
        migrations.CreateModel(
            name="PartyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "當事者性別名稱",
                    models.CharField(
                        choices=[
                            ("男", "男"),
                            ("女", "女"),
                            ("肇事逃逸尚未查獲", "肇事逃逸尚未查獲"),
                            ("無或物(動物、堆置物)", "無或物(動物、堆置物)"),
                        ],
                        default="男",
                        max_length=15,
                    ),
                ),
                ("當事者事故發生時年齡", models.IntegerField()),
                (
                    "保護裝備名稱",
                    models.CharField(
                        choices=[
                            ("無", "無"),
                            (
                                "未戴案全帽或未繫安全帶(未使用幼童安全椅)",
                                "未戴案全帽或未繫安全帶(未使用幼童安全椅)",
                            ),
                            (
                                "戴安全帽或繫安全帶(使用幼童安全椅)",
                                "戴安全帽或繫安全帶(使用幼童安全椅)",
                            ),
                            ("其他(行人、慢車駕駛人)", "其他(行人、慢車駕駛人)"),
                            (
                                "其他(無需使用保護裝備之人)",
                                "其他(無需使用保護裝備之人)",
                            ),
                            ("不明", "不明"),
                        ],
                        default="無",
                        max_length=25,
                    ),
                ),
                (
                    "當事者行動狀態子類別名稱",
                    models.CharField(
                        choices=[
                            ("無", "無"),
                            ("向左變換車道", "向左變換車道"),
                            ("倒車", "倒車"),
                            ("向右變換車道", "向右變換車道"),
                            ("超車(含超越)", "超車(含超越)"),
                            ("奔跑", "奔跑"),
                            ("向前直行中", "向前直行中"),
                            ("起步", "起步"),
                            ("等待(引擎未熄火)", "等待(引擎未熄火)"),
                            ("靜立(止)", "靜立(止)"),
                            ("上、下車", "上、下車"),
                            ("迴轉或橫越道路中", "迴轉或橫越道路中"),
                            ("急減速或急停止", "急減速或急停止"),
                            ("右轉彎", "右轉彎"),
                            ("插入行列", "插入行列"),
                            ("步行", "步行"),
                            ("其他", "其他"),
                            ("停車操作中", "停車操作中"),
                            ("不明", "不明"),
                            ("靜止(引擎熄火)", "靜止(引擎熄火)"),
                            ("左轉彎", "左轉彎"),
                        ],
                        default="無",
                        max_length=10,
                    ),
                ),
                ("車輛撞擊部位子類別名稱_最初", models.CharField(max_length=10)),
                (
                    "車輛撞擊部位大類別名稱_其他",
                    models.CharField(
                        choices=[
                            ("無", "無"),
                            ("機車", "機車"),
                            ("汽車", "汽車"),
                            ("其他", "其他"),
                        ],
                        default="無",
                        max_length=25,
                    ),
                ),
                ("車輛撞擊部位子類別名稱_其他", models.CharField(max_length=10)),
                (
                    "accident_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.accidentrecords",
                    ),
                ),
                (
                    "當事者區分_類別_大類別名稱_車種",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport_subsidiary.vehicletype",
                    ),
                ),
            ],
            options={
                "verbose_name": "肇事人紀錄",
                "verbose_name_plural": "肇事人紀錄",
                "db_table_comment": "肇事人紀錄表",
            },
        ),
        migrations.CreateModel(
            name="RoadConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "道路型態大類別名稱",
                    models.CharField(
                        choices=[
                            ("平交道", "平交道"),
                            ("單路部分", "單路部分"),
                            ("圓環廣場", "圓環廣場"),
                            ("交岔路", "交岔路"),
                        ],
                        default="平交道",
                        max_length=4,
                    ),
                ),
                (
                    "道路型態子類別名稱",
                    models.CharField(
                        choices=[
                            ("彎曲路及附近", "彎曲路及附近"),
                            ("圓環", "圓環"),
                            ("有遮斷器", "有遮斷器"),
                            ("涵洞", "涵洞"),
                            ("廣場", "廣場"),
                            ("三岔路", "三岔路"),
                            ("地下道", "地下道"),
                            ("高架道路", "高架道路"),
                            ("直路", "直路"),
                            ("坡路", "坡路"),
                            ("四岔路", "四岔路"),
                            ("無遮斷器", "無遮斷器"),
                            ("橋樑", "橋樑"),
                            ("多岔路", "多岔路"),
                            ("巷弄", "巷弄"),
                            ("其他", "其他"),
                            ("隧道", "隧道"),
                        ],
                        default="彎曲路及附近",
                        max_length=10,
                    ),
                ),
                (
                    "事故位置大類別名稱",
                    models.CharField(
                        choices=[
                            ("路段", "路段"),
                            ("交叉路口", "交叉路口"),
                            ("交流道", "交流道"),
                            ("其他", "其他"),
                        ],
                        default="路段",
                        max_length=4,
                    ),
                ),
                (
                    "路面狀況_路面鋪裝名稱",
                    models.CharField(
                        choices=[
                            ("柏油", "柏油"),
                            ("碎石", "碎石"),
                            ("水泥", "水泥"),
                            ("無鋪裝", "無鋪裝"),
                            ("其他鋪裝", "其他鋪裝"),
                        ],
                        default="柏油",
                        max_length=4,
                    ),
                ),
                (
                    "路面狀況_路面狀態名稱",
                    models.CharField(
                        choices=[
                            ("濕潤", "濕潤"),
                            ("冰雪", "冰雪"),
                            ("油滑", "油滑"),
                            ("乾燥", "乾燥"),
                            ("泥濘", "泥濘"),
                        ],
                        default="濕潤",
                        max_length=2,
                    ),
                ),
                (
                    "路面狀況_路面缺陷名稱",
                    models.CharField(
                        choices=[
                            ("無缺陷", "無缺陷"),
                            ("路面鬆軟", "路面鬆軟"),
                            ("有坑洞", "有坑洞"),
                            ("突出(高低)不平", "突出(高低)不平"),
                        ],
                        default="無缺陷",
                        max_length=10,
                    ),
                ),
                (
                    "道路障礙_障礙物名稱",
                    models.CharField(
                        choices=[
                            ("道路工事(程)中", "道路工事(程)中"),
                            ("路上有停車", "路上有停車"),
                            ("有堆積物", "有堆積物"),
                            ("無障礙物", "無障礙物"),
                            ("其他障礙物", "其他障礙物"),
                        ],
                        default="道路工事(程)中",
                        max_length=10,
                    ),
                ),
                (
                    "道路障礙_視距品質名稱",
                    models.CharField(
                        choices=[
                            ("無遮蔽", "無遮蔽"),
                            ("不良", "不良"),
                            ("良好", "良好"),
                        ],
                        default="無遮蔽",
                        max_length=10,
                    ),
                ),
                (
                    "道路障礙_視距名稱",
                    models.CharField(
                        choices=[
                            ("坡道", "坡道"),
                            ("樹木、農作物", "樹木、農作物"),
                            ("彎道", "彎道"),
                            ("路上停放車輛", "路上停放車輛"),
                            ("良好", "良好"),
                            ("建築物", "建築物"),
                            ("其他", "其他"),
                        ],
                        default="坡道",
                        max_length=10,
                    ),
                ),
                (
                    "accident_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.accidentrecords",
                    ),
                ),
            ],
            options={
                "verbose_name": "道路狀況",
                "verbose_name_plural": "道路狀況",
                "db_table_comment": "道路狀況表",
            },
        ),
        migrations.CreateModel(
            name="TrafficFacilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "號誌_號誌種類名稱",
                    models.CharField(
                        choices=[
                            ("行車管制號誌", "行車管制號誌"),
                            ("無號誌", "無號誌"),
                            ("閃光號誌", "閃光號誌"),
                            (
                                "行車管制號誌(附設行人專用號誌)",
                                "行車管制號誌(附設行人專用號誌)",
                            ),
                        ],
                        default="行車管制號誌",
                        max_length=20,
                    ),
                ),
                (
                    "號誌_號誌動作名稱",
                    models.CharField(
                        choices=[
                            ("無號誌", "無號誌"),
                            ("無動作", "無動作"),
                            ("正常", "正常"),
                            ("不正常", "不正常"),
                        ],
                        default="無號誌",
                        max_length=3,
                    ),
                ),
                (
                    "accident_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.accidentrecords",
                    ),
                ),
            ],
            options={
                "verbose_name": "交通設施",
                "verbose_name_plural": "交通設施",
                "db_table_comment": "交通設施表",
            },
        ),
    ]
