# Generated by Django 5.0.6 on 2024-06-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccidentRecords",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("發生年度", models.CharField(blank=True, max_length=4, null=True)),
                ("發生月份", models.CharField(blank=True, max_length=2, null=True)),
                ("發生日期", models.CharField(blank=True, max_length=8, null=True)),
                ("發生時間", models.CharField(blank=True, max_length=6, null=True)),
                ("事故類別名稱", models.CharField(blank=True, max_length=2, null=True)),
                ("發生地點", models.CharField(blank=True, max_length=80, null=True)),
                ("天候名稱", models.CharField(blank=True, max_length=3, null=True)),
                ("光線名稱", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "經度",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "緯度",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "db_table": "accident_records",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CauseAnalysis",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "肇因研判大類別名稱_主要",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "肇因研判子類別名稱_主要",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "肇因研判子類別名稱_個別",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "肇事逃逸類別名稱_是否肇逃",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
            ],
            options={
                "db_table": "cause_analysis",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PartyInfo",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "當事者性別名稱",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("當事者事故發生時年齡", models.IntegerField(blank=True, null=True)),
                (
                    "保護裝備名稱",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "當事者行動狀態子類別名稱",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "車輛撞擊部位子類別名稱_最初",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "車輛撞擊部位大類別名稱_其他",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "車輛撞擊部位子類別名稱_其他",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "party_info",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RoadConditions",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "道路型態大類別名稱",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "道路型態子類別名稱",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "事故位置大類別名稱",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "路面狀況_路面鋪裝名稱",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "路面狀況_路面狀態名稱",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "路面狀況_路面缺陷名稱",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "道路障礙_障礙物名稱",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "道路障礙_視距品質名稱",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "道路障礙_視距名稱",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "road_conditions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TrafficFacilities",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "號誌_號誌種類名稱",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "號誌_號誌動作名稱",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
            ],
            options={
                "db_table": "traffic_facilities",
                "managed": False,
            },
        ),
    ]
