# Generated by Django 5.0.6 on 2024-06-19 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0001_initial"),
        (
            "transport_subsidiary",
            "0002_alter_unitname_options_alter_vehicletype_options",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="accidentrecords",
            name="發生地點",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="accidentrecords",
            name="發生年度",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="accidentrecords",
            name="發生日期",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="accidentrecords",
            name="發生時間",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="accidentrecords",
            name="發生月份",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="accidentrecords",
            name="經度",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="accidentrecords",
            name="緯度",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="accidentrecords",
            name="處理單位名稱警局層",
            field=models.ForeignKey(
                db_column="處理單位名稱警局層",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="transport_subsidiary.unitname",
            ),
        ),
        migrations.AlterField(
            model_name="causeanalysis",
            name="肇因研判子類別名稱_主要",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="causeanalysis",
            name="肇因研判子類別名稱_個別",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="partyinfo",
            name="當事者事故發生時年齡",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="partyinfo",
            name="當事者區分_類別_大類別名稱_車種",
            field=models.ForeignKey(
                db_column="當事者區分_類別_大類別名稱_車種",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="transport_subsidiary.vehicletype",
            ),
        ),
    ]
