# Generated by Django 5.0.6 on 2024-06-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accidentrecords",
            name="事故類別名稱",
            field=models.CharField(
                choices=[("A1", "A1"), ("A2", "A2")], default="A1", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="partyinfo",
            name="車輛撞擊部位子類別名稱_其他",
            field=models.CharField(
                choices=[
                    ("左前車頭(身)", "左前車頭(身)"),
                    ("非汽(機)車", "非汽(機)車"),
                    ("後車尾", "後車尾"),
                    ("左側車身", "左側車身"),
                    ("右後車尾(身)", "右後車尾(身)"),
                    ("車底", "車底"),
                    ("不明", "不明"),
                    ("右側車身", "右側車身"),
                    ("車頂", "車頂"),
                    ("右前車頭(身)", "右前車頭(身)"),
                    ("左後車尾(身)", "左後車尾(身)"),
                    ("前車頭", "前車頭"),
                ],
                default="左前車頭(身)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="partyinfo",
            name="車輛撞擊部位子類別名稱_最初",
            field=models.CharField(
                choices=[
                    ("左前車頭(身)", "左前車頭(身)"),
                    ("非汽(機)車", "非汽(機)車"),
                    ("後車尾", "後車尾"),
                    ("左側車身", "左側車身"),
                    ("右後車尾(身)", "右後車尾(身)"),
                    ("車底", "車底"),
                    ("不明", "不明"),
                    ("右側車身", "右側車身"),
                    ("車頂", "車頂"),
                    ("右前車頭(身)", "右前車頭(身)"),
                    ("左後車尾(身)", "左後車尾(身)"),
                    ("前車頭", "前車頭"),
                ],
                default="左前車頭(身)",
                max_length=10,
            ),
        ),
    ]
