# Generated by Django 5.0.6 on 2024-06-15 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_accidentrecords_options_and_more'),
        ('transport_subsidiary', '0003_alter_unitname_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='accidentrecords',
            table_comment='事故紀錄表',
        ),
        migrations.AlterModelTableComment(
            name='causeanalysis',
            table_comment='原因分析表',
        ),
        migrations.AlterModelTableComment(
            name='partyinfo',
            table_comment='肇事人紀錄表',
        ),
        migrations.AlterModelTableComment(
            name='roadconditions',
            table_comment='道路狀況表',
        ),
        migrations.AlterModelTableComment(
            name='trafficfacilities',
            table_comment='交通設施表',
        ),
        migrations.AddField(
            model_name='accidentrecords',
            name='處理單位名稱警局層',
            field=models.ForeignKey(blank=True, db_column='處理單位名稱警局層', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transport_subsidiary.unitname'),
        ),
        migrations.AddField(
            model_name='causeanalysis',
            name='accident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transport.accidentrecords'),
        ),
        migrations.AddField(
            model_name='partyinfo',
            name='accident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transport.accidentrecords'),
        ),
        migrations.AddField(
            model_name='partyinfo',
            name='當事者區分_類別_大類別名稱_車種',
            field=models.ForeignKey(blank=True, db_column='當事者區分_類別_大類別名稱_車種', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transport_subsidiary.vehicletype'),
        ),
        migrations.AddField(
            model_name='roadconditions',
            name='accident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transport.accidentrecords'),
        ),
        migrations.AddField(
            model_name='trafficfacilities',
            name='accident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transport.accidentrecords'),
        ),
        migrations.AlterField(
            model_name='accidentrecords',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='accidentrecords',
            name='事故類別名稱',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2')], default='A1', max_length=2),
        ),
        migrations.AlterField(
            model_name='accidentrecords',
            name='光線名稱',
            field=models.CharField(choices=[('夜間(或隧道、地下道、涵洞)有照明', '夜間(或隧道、地下道、涵洞)有照明'), ('夜間(或隧道、地下道、涵洞)無照明', '夜間(或隧道、地下道、涵洞)無照明'), ('有照明未開啟或故障', '有照明未開啟或故障'), ('晨或暮光', '晨或暮光'), ('日間自然光線', '日間自然光線')], default='夜間(或隧道、地下道、涵洞)有照明', max_length=20),
        ),
        migrations.AlterField(
            model_name='accidentrecords',
            name='天候名稱',
            field=models.CharField(choices=[('晴', '晴'), ('雪', '雪'), ('風沙', '風沙'), ('暴雨', '暴雨'), ('強風', '強風'), ('雨', '雨'), ('陰', '陰'), ('霧或煙', '霧或煙')], default='晴', max_length=3),
        ),
        migrations.AlterField(
            model_name='accidentrecords',
            name='發生地點',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='accidentrecords',
            name='發生年度',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='accidentrecords',
            name='發生日期',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='accidentrecords',
            name='發生時間',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='accidentrecords',
            name='發生月份',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='accidentrecords',
            name='經度',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='accidentrecords',
            name='緯度',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='causeanalysis',
            name='肇事逃逸類別名稱_是否肇逃',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='causeanalysis',
            name='肇因研判大類別名稱_主要',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='causeanalysis',
            name='肇因研判子類別名稱_主要',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='causeanalysis',
            name='肇因研判子類別名稱_個別',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='partyinfo',
            name='保護裝備名稱',
            field=models.CharField(choices=[('無', '無'), ('未戴案全帽或未繫安全帶(未使用幼童安全椅)', '未戴案全帽或未繫安全帶(未使用幼童安全椅)'), ('戴安全帽或繫安全帶(使用幼童安全椅)', '戴安全帽或繫安全帶(使用幼童安全椅)'), ('其他(行人、慢車駕駛人)', '其他(行人、慢車駕駛人)'), ('其他(無需使用保護裝備之人)', '其他(無需使用保護裝備之人)'), ('不明', '不明')], default='無', max_length=25),
        ),
        migrations.AlterField(
            model_name='partyinfo',
            name='當事者事故發生時年齡',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partyinfo',
            name='當事者性別名稱',
            field=models.CharField(choices=[('男', '男'), ('女', '女'), ('肇事逃逸尚未查獲', '肇事逃逸尚未查獲'), ('無或物(動物、堆置物)', '無或物(動物、堆置物)')], default='男', max_length=15),
        ),
        migrations.AlterField(
            model_name='partyinfo',
            name='當事者行動狀態子類別名稱',
            field=models.CharField(choices=[('無', '無'), ('向左變換車道', '向左變換車道'), ('倒車', '倒車'), ('向右變換車道', '向右變換車道'), ('超車(含超越)', '超車(含超越)'), ('奔跑', '奔跑'), ('向前直行中', '向前直行中'), ('起步', '起步'), ('等待(引擎未熄火)', '等待(引擎未熄火)'), ('靜立(止)', '靜立(止)'), ('上、下車', '上、下車'), ('迴轉或橫越道路中', '迴轉或橫越道路中'), ('急減速或急停止', '急減速或急停止'), ('右轉彎', '右轉彎'), ('插入行列', '插入行列'), ('步行', '步行'), ('其他', '其他'), ('停車操作中', '停車操作中'), ('不明', '不明'), ('靜止(引擎熄火)', '靜止(引擎熄火)'), ('左轉彎', '左轉彎')], default='無', max_length=10),
        ),
        migrations.AlterField(
            model_name='partyinfo',
            name='車輛撞擊部位大類別名稱_其他',
            field=models.CharField(choices=[('無', '無'), ('機車', '機車'), ('汽車', '汽車'), ('其他', '其他')], default='無', max_length=25),
        ),
        migrations.AlterField(
            model_name='partyinfo',
            name='車輛撞擊部位子類別名稱_其他',
            field=models.CharField(choices=[('左前車頭(身)', '左前車頭(身)'), ('非汽(機)車', '非汽(機)車'), ('後車尾', '後車尾'), ('左側車身', '左側車身'), ('右後車尾(身)', '右後車尾(身)'), ('車底', '車底'), ('不明', '不明'), ('右側車身', '右側車身'), ('車頂', '車頂'), ('右前車頭(身)', '右前車頭(身)'), ('左後車尾(身)', '左後車尾(身)'), ('前車頭', '前車頭')], default='左前車頭(身)', max_length=10),
        ),
        migrations.AlterField(
            model_name='partyinfo',
            name='車輛撞擊部位子類別名稱_最初',
            field=models.CharField(choices=[('左前車頭(身)', '左前車頭(身)'), ('非汽(機)車', '非汽(機)車'), ('後車尾', '後車尾'), ('左側車身', '左側車身'), ('右後車尾(身)', '右後車尾(身)'), ('車底', '車底'), ('不明', '不明'), ('右側車身', '右側車身'), ('車頂', '車頂'), ('右前車頭(身)', '右前車頭(身)'), ('左後車尾(身)', '左後車尾(身)'), ('前車頭', '前車頭')], default='左前車頭(身)', max_length=10),
        ),
        migrations.AlterField(
            model_name='roadconditions',
            name='事故位置大類別名稱',
            field=models.CharField(choices=[('路段', '路段'), ('交叉路口', '交叉路口'), ('交流道', '交流道'), ('其他', '其他')], default='路段', max_length=4),
        ),
        migrations.AlterField(
            model_name='roadconditions',
            name='路面狀況_路面狀態名稱',
            field=models.CharField(choices=[('濕潤', '濕潤'), ('冰雪', '冰雪'), ('油滑', '油滑'), ('乾燥', '乾燥'), ('泥濘', '泥濘')], default='濕潤', max_length=2),
        ),
        migrations.AlterField(
            model_name='roadconditions',
            name='路面狀況_路面缺陷名稱',
            field=models.CharField(choices=[('無缺陷', '無缺陷'), ('路面鬆軟', '路面鬆軟'), ('有坑洞', '有坑洞'), ('突出(高低)不平', '突出(高低)不平')], default='無缺陷', max_length=10),
        ),
        migrations.AlterField(
            model_name='roadconditions',
            name='路面狀況_路面鋪裝名稱',
            field=models.CharField(choices=[('柏油', '柏油'), ('碎石', '碎石'), ('水泥', '水泥'), ('無鋪裝', '無鋪裝'), ('其他鋪裝', '其他鋪裝')], default='柏油', max_length=4),
        ),
        migrations.AlterField(
            model_name='roadconditions',
            name='道路型態大類別名稱',
            field=models.CharField(choices=[('平交道', '平交道'), ('單路部分', '單路部分'), ('圓環廣場', '圓環廣場'), ('交岔路', '交岔路')], default='平交道', max_length=4),
        ),
        migrations.AlterField(
            model_name='roadconditions',
            name='道路型態子類別名稱',
            field=models.CharField(choices=[('彎曲路及附近', '彎曲路及附近'), ('圓環', '圓環'), ('有遮斷器', '有遮斷器'), ('涵洞', '涵洞'), ('廣場', '廣場'), ('三岔路', '三岔路'), ('地下道', '地下道'), ('高架道路', '高架道路'), ('直路', '直路'), ('坡路', '坡路'), ('四岔路', '四岔路'), ('無遮斷器', '無遮斷器'), ('橋樑', '橋樑'), ('多岔路', '多岔路'), ('巷弄', '巷弄'), ('其他', '其他'), ('隧道', '隧道')], default='彎曲路及附近', max_length=10),
        ),
        migrations.AlterField(
            model_name='roadconditions',
            name='道路障礙_視距名稱',
            field=models.CharField(choices=[('坡道', '坡道'), ('樹木、農作物', '樹木、農作物'), ('彎道', '彎道'), ('路上停放車輛', '路上停放車輛'), ('良好', '良好'), ('建築物', '建築物'), ('其他', '其他')], default='坡道', max_length=10),
        ),
        migrations.AlterField(
            model_name='roadconditions',
            name='道路障礙_視距品質名稱',
            field=models.CharField(choices=[('無遮蔽', '無遮蔽'), ('不良', '不良'), ('良好', '良好')], default='無遮蔽', max_length=10),
        ),
        migrations.AlterField(
            model_name='roadconditions',
            name='道路障礙_障礙物名稱',
            field=models.CharField(choices=[('道路工事(程)中', '道路工事(程)中'), ('路上有停車', '路上有停車'), ('有堆積物', '有堆積物'), ('無障礙物', '無障礙物'), ('其他障礙物', '其他障礙物')], default='道路工事(程)中', max_length=10),
        ),
        migrations.AlterField(
            model_name='trafficfacilities',
            name='號誌_號誌動作名稱',
            field=models.CharField(choices=[('無號誌', '無號誌'), ('無動作', '無動作'), ('正常', '正常'), ('不正常', '不正常')], default='無號誌', max_length=3),
        ),
        migrations.AlterField(
            model_name='trafficfacilities',
            name='號誌_號誌種類名稱',
            field=models.CharField(choices=[('行車管制號誌', '行車管制號誌'), ('無號誌', '無號誌'), ('閃光號誌', '閃光號誌'), ('行車管制號誌(附設行人專用號誌)', '行車管制號誌(附設行人專用號誌)')], default='行車管制號誌', max_length=20),
        ),
    ]
